[package]
description = "Matrix load testing tool"
edition = "2021"
name = "matrix-load-testing-tool"
repository = "https://github.com/decentraland/matrix-load-testing-tool"
version = "0.1.0"

[dependencies]
clap = {version = "3.1.8", features = ["derive"]}
config = "0.13"
env_logger = "0.9.0"
futures = "0.3.21"
indicatif = "0.16.2"
lipsum = "0.8.0"
log = "0.4.16"
rand = "0.8.5"
regex = "1"
serde = "1.0.136"
serde_with = "1.12.1"
serde_yaml = "0.8.23"
strum = {version = "0.21", features = ["derive"]}
tokio = {version = "1", features = ["full"]}
tokio-context = "0.1.3"

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "35f598a"

[lib]
name = "matrix_load_testing_tool"
path = "src/lib.rs"

# On Windows
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools-preview
# ```
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
# On Linux:
# - Ubuntu, `sudo apt-get install lld clang`
# - Arch, `sudo pacman -S lld clang`
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
# On MacOS, `brew install michaeleisel/zld/zld`
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]
