[package]
name = "matrix-load-testing-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
matrix-sdk = "0.4.1"
tokio = { version = "1", features = ["full"] }
lipsum = "0.8.0"
futures = "0.3.21"
log = "0.4.16"
env_logger = "0.9.0"
indicatif = "0.16.2"

[lib]
name = "matrix_load_testing_tool"
path = "src/lib.rs"