[package]
name = "matrix-load-testing-tool"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
matrix-sdk = "0.4.1"
tokio = { version = "1", features = ["full"] }