[server]
homeserver = "http://localhost"
wk_login = true

[simulation]
ticks = 4000
tick_duration_in_secs = 5
max_users = 5000
users_per_tick = 15
grace_period_duration_in_secs = 30
output = "output"
channels_per_user = 5
channels_load = false
allow_get_channel_members = false
interaction_ratios_config = '{"log_out":75,"leave_channel":70,"get_channel_members":60,"create_channel":50,"join_channel":35,"update_status":25,"add_friend":3,"send_channel_message":10}'

[requests]
retry_enabled = true