# Total steps
total_steps = 2
# Users to be created per step
users_per_step = 100
# Friendships (rooms) based on: total possible friendships * friendship ratio
friendship_ratio = 0.1
# Step duration where users interact each other
step_duration_in_secs = 30
# Max users to act per second during a step
max_users_to_act_per_tick = 100
# Time to wait for all messages to be delivered, after that time they are considered as lost
waiting_period = 30
# Enable retry request configuration 
retry_request_config = false
# User creation retry attempts (not related to retry_request_config)
user_creation_retry_attempts = 5
# Max throughput allowed for users registration 
user_creation_throughput = 10
# Max throughput allowed for room creation 
room_creation_throughput = 20
