# Total steps
total_steps = 2
# Users to be created per step
users_per_step = 50
# Friendhips (rooms) based on: total possible friendships * friendship ratio
friendship_ratio = 0.5
# Step duration where users interact each other
step_duration_in_secs = 30
# Max users to act per second during a step
max_users_to_act_per_tick = 100
# Time to wait for all messages to be delivered, after that time they are considered as lost
waiting_period = 30
# Enable retry request configuration 
retry_request_config = false
# User creation retry attempts (not related to retry_request_config)
user_creation_retry_attempts = 5