name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: moliva/audit-check@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # FIXME - ignoring due to chrono possible segfaults - moliva - 2022/05/09
          ignore: "RUSTSEC-2020-0071"
